version: 2

updates:
  # Keep NuGet packages up to date
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "unrealbg"
    assignees:
      - "unrealbg"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "nuget"
    # Group minor and patch updates together
    groups:
      aspnet-core:
        patterns:
          - "Microsoft.AspNetCore*"
          - "Microsoft.Extensions*"
      entityframework:
        patterns:
          - "Microsoft.EntityFrameworkCore*"
      testing:
        patterns:
          - "Microsoft.NET.Test.Sdk"
          - "xunit*"
          - "coverlet*"
          - "Microsoft.AspNetCore.Mvc.Testing"
      aspire:
        patterns:
          - "Aspire.*"
      opentelemetry:
        patterns:
          - "OpenTelemetry*"
      serilog:
        patterns:
          - "Serilog*"

  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "unrealbg"
    assignees:
      - "unrealbg"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"